myOceanByTeam3/myOceanGradle

src/main/resources/templates/app/host/host.html

[모임 등록]진행 사항 옮김 + 문구 조금 수정

---

src/main/resources/static/css/bulletin_board/bulletin.css
src/main/resources/templates/app/bulletin_board/bulletin_board.html
src/main/resources/templates/app/mySpace/mySpace.html

[bulletin] - html, css
모임작성버튼 추가

손호현, 22.11.25

---

src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/fix/chatting.js
src/main/resources/templates/app/community/community_write.html

1. 커뮤니티 글 작성 시 내용 불러오기
2. 채팅창 css 수정

[20221125 홍준성 -3]

---

src/main/java/com/example/myoceanproject/domain/AlarmDTO.java
src/main/java/com/example/myoceanproject/domain/AskDTO.java
src/main/java/com/example/myoceanproject/domain/ChattingDTO.java
src/main/java/com/example/myoceanproject/domain/CommunityFileDTO.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/domain/DiaryDTO.java
src/main/java/com/example/myoceanproject/domain/GroupScheduleDTO.java
src/main/java/com/example/myoceanproject/domain/PointDTO.java
src/main/java/com/example/myoceanproject/domain/QuestDTO.java
src/main/java/com/example/myoceanproject/entity/Alarm.java
src/main/java/com/example/myoceanproject/entity/Ask.java
src/main/java/com/example/myoceanproject/entity/Chatting.java
src/main/java/com/example/myoceanproject/entity/CommunityFile.java
src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/entity/GroupSchedule.java
src/main/java/com/example/myoceanproject/entity/Point.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/java/com/example/myoceanproject/entity/QuestAchievement.java
src/main/java/com/example/myoceanproject/entity/ToDoList.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/resources/templates/app/community/community_write.html

[20221126 홍준성 -1]

---

src/main/java/com/example/myoceanproject/domain/AlarmDTO.java
src/main/java/com/example/myoceanproject/domain/ChattingDTO.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/domain/CommunityReplyDTO.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/entity/Alarm.java
src/main/java/com/example/myoceanproject/entity/Chatting.java
src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/entity/CommunityReply.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/AlarmRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepository.java
src/main/java/com/example/myoceanproject/type/AskCategory.java
src/main/java/com/example/myoceanproject/type/AskStatus.java
src/main/resources/application.yml
src/test/java/com/example/myoceanproject/dtoTest/AlarmTest.java

Alarm save 단위테스트 진행, UserRepository, AlarmRepository 추가, Enum에 toString 추가, 참조 받는 쪽 부터 save를 해줘야함

Alarm save 단위테스트 진행, UserRepository, AlarmRepository 추가

---

src/main/java/com/example/myoceanproject/entity/Alarm.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/AlarmRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepository.java
src/test/java/com/example/myoceanproject/dtoTest/AlarmTest.java

[20221127 홍준성 -1]

---

src/main/java/com/example/myoceanproject/domain/ChattingDTO.java
src/main/java/com/example/myoceanproject/repository/ChattingRepository.java
src/main/java/com/example/myoceanproject/repository/GroupRepository.java
src/main/java/com/example/myoceanproject/type/UserLoginMethod.java
src/test/java/com/example/myoceanproject/dtoTest/ChattingTest.java
src/test/java/com/example/myoceanproject/dtoTest/QuestTest.java

QuestTest 완료, ChattingTest 진행중

QuestTest 완료, ChattingTest 진행중

---

src/main/java/com/example/myoceanproject/entity/ToDoList.java
src/main/java/com/example/myoceanproject/repository/CommunityPostRepository.java
src/main/java/com/example/myoceanproject/repository/TodoListRepository.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityPostTest.java
src/test/java/com/example/myoceanproject/dtoTest/TodolistTest.java

communitypost, todolist

---

src/main/java/com/example/myoceanproject/domain/PointDTO.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/entity/Alarm.java
src/main/java/com/example/myoceanproject/entity/Point.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/PointRepository.java
src/main/resources/application.yml
src/test/java/com/example/myoceanproject/dtoTest/PointTest.java
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

[20221127 홍준성 -2]

---

src/main/java/com/example/myoceanproject/domain/DiaryDTO.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/repository/DiaryRepository.java
src/test/java/com/example/myoceanproject/dtoTest/DiaryTest.java

이호영 2211272052 단위테스트 diary 진행중

이호영 2211272052 단위테스트

---

src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/type/CommunityCategory.java

20221128 배다빈

---

src/main/java/com/example/myoceanproject/entity/Ask.java
src/main/java/com/example/myoceanproject/entity/CommunityFile.java
src/main/java/com/example/myoceanproject/entity/CommunityLike.java
src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/repository/AskRepository.java
src/main/java/com/example/myoceanproject/repository/CommunityPostRepository.java
src/main/java/com/example/myoceanproject/type/AskCategory.java
src/test/java/com/example/myoceanproject/dtoTest/AskTest.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityLikeTest.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityPostTest.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityReplyTest.java

이호영 2211291033 작업사항

---

src/main/java/com/example/myoceanproject/repository/AskRepository.java
src/test/java/com/example/myoceanproject/dtoTest/AskTest.java

이호영 2211291636 작업사항

---

src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java

[20221129 홍준성 -1]

---

src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/repository/AskRepository.java
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java

[20221129 홍준성 -2]

---

src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/repository/CommunityFileCustomRepository.java
src/main/java/com/example/myoceanproject/repository/CommunityFileRepository.java
src/main/java/com/example/myoceanproject/repository/CommunityFileRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/CommunityPostRepository.java
src/main/resources/application.yml
src/test/java/com/example/myoceanproject/dtoTest/CommunityPostTest.java

커뮤니티 파일 사용자 레파지토리 생성 및 메소드 추가
커뮤니티 파일 단위 테스트 CRUD 진행

커뮤니티, 커뮤니티 파일 관련 수정

---

src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/entity/GroupMember.java
src/main/java/com/example/myoceanproject/entity/GroupSchedule.java
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupScheduleTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java

[20221129 홍준성-3]

---

src/test/java/com/example/myoceanproject/dtoTest/GroupScheduleTest.java

[20221129 홍준성 -5]

---

src/main/java/com/example/myoceanproject/entity/CommunityReply.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityReplyTest.java

커뮤니티 리플라이 단위테스트

---

src/main/java/com/example/myoceanproject/domain/QuestDTO.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/java/com/example/myoceanproject/entity/QuestAchievement.java
src/test/java/com/example/myoceanproject/dtoTest/AlarmTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupScheduleTest.java
src/test/java/com/example/myoceanproject/dtoTest/QuestAchievementTest.java
src/test/java/com/example/myoceanproject/dtoTest/QuestTest.java

Quest, QuestAchivement 기본 단위테스트 완료

[20221130 홍준성 -1]

---

src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/entity/ToDoList.java
src/test/java/com/example/myoceanproject/dtoTest/DiaryTest.java
src/test/java/com/example/myoceanproject/dtoTest/TodolistTest.java

[20221130 홍준성 -2]

---

src/main/java/com/example/myoceanproject/domain/AskDTO.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/entity/Ask.java
src/main/java/com/example/myoceanproject/entity/User.java
src/test/java/com/example/myoceanproject/dtoTest/AskTest.java
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2211301541 작업사항

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/service/GroupBoardService.java
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html

[20221130 홍준성 -8]

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html

[20221201 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/resources/static/css/Join/join_in.css
src/main/resources/static/js/Join/join_in.js
src/main/resources/static/js/Join/join_in_second.js
src/main/resources/templates/app/Join/join_in.html
src/main/resources/templates/app/Join/join_in_second.html
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212011509 작업사항

---

src/main/java/com/example/myoceanproject/controller/manager/ManagerController.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityLikeTest.java

[20221201배다빈]

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html

[20221201 홍준성 -3]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/resources/static/js/Join/join_in.js
src/main/resources/static/js/Join/join_in_second.js
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212011746 작업사항

---

src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/resources/static/js/Join/join_in.js
src/main/resources/static/js/login/login.js
src/main/resources/templates/app/login/login.html
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212012239 작업사항

---

build.gradle
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html

[20221202 홍준성 -2]

---

src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/domain/UserFindDTO.java
src/main/java/com/example/myoceanproject/entity/UserFind.java
src/main/java/com/example/myoceanproject/repository/UserFindRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepository.java
src/main/resources/application.yml
src/main/resources/static/js/login/findPw.js
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/fix/header.html
src/main/resources/templates/app/login/findPw.html
src/test/java/com/example/myoceanproject/dtoTest/UserFindTest.java
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212021708 작업사항

---

src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/resources/application.yml
src/main/resources/static/js/login/changePassword.js
src/main/resources/templates/app/login/findPw.html
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212021958 작업사항  확인부탁드립니다.

이호영 2212021958 작업사항

---

src/main/java/com/example/myoceanproject/controller/manager/ManagerController.java
src/main/java/com/example/myoceanproject/controller/manager/PostController.java
src/main/java/com/example/myoceanproject/controller/manager/ReplyController.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/domain/CommunityReplyDTO.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/community/reply/CommunityReplyCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/reply/CommunityReplyRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/main/java/com/example/myoceanproject/service/community/CommunityReplyService.java
src/main/resources/static/css/manager/admin_counseling_board_reply.css
src/main/resources/static/css/manager/admin_free_board_reply.css
src/main/resources/static/js/manager/admin_counselling_board_reply.js
src/main/resources/templates/app/manager/admin_counseling_board_reply.html
src/main/resources/templates/app/manager/admin_free_board.html
src/main/resources/templates/app/manager/admin_free_board_reply.html
src/test/java/com/example/myoceanproject/dtoTest/CommunityPostTest.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityReplyTest.java

고민상담 댓글 불러오기/페이징/검색
게시판 댓글 불러오기/페이징/검색
게시글 &게시글과 관련된 항목전체 삭제하기(좋아요, 파일, 댓글)
댓글 삭제하기

[20221203 배다빈]

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/bulletin_board/bulletin_board.html
src/main/resources/templates/app/fix/header.html
src/main/resources/templates/app/host/host.html
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java
src/test/java/com/example/myoceanproject/serviceTest/GroupServiceTest.java

[20221203 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/bulletin_board/BulletinboardController.java
src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/resources/static/js/bulletin_board/bulletin_board.js
src/main/resources/templates/app/bulletin_board/bulletin_board.html
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/fix/headerModify.html
src/test/java/com/example/myoceanproject/dtoTest/ChattingTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java
src/test/java/com/example/myoceanproject/serviceTest/GroupServiceTest.java

모임 전체 페이지 출력
모임 상세 페이지 수정
find 테스트

[20221203 홍준성 -2]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/controller/myPage/MyPageController.java
src/main/resources/static/js/Join/join_in.js
src/main/resources/static/js/login/changePassword.js
src/main/resources/static/js/login/findPw.js
src/main/resources/static/js/login/login.js
src/main/resources/static/js/myPage/myPage.js
src/main/resources/static/js/myPage/passwordChange.js
src/main/resources/templates/app/myPage/myPage.html
src/main/resources/templates/app/myPage/passwordChange.html

이호영 2212031830 작업사항

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/controller/manager/ManagePostController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageReplyController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/controller/manager/ManagerController.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/community/reply/CommunityReplyCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/reply/CommunityReplyRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/main/resources/application.yml
src/main/resources/static/css/manager/admin_user_list.css
src/main/resources/static/js/manager/admin_user_list.js
src/main/resources/templates/app/manager/admin_user_list.html

[20221204 배다빈]

---

src/main/java/com/example/myoceanproject/config/WebSocketConfig.java
src/main/java/com/example/myoceanproject/config/WebSocketMessageBrokerConfig.java
src/main/java/com/example/myoceanproject/controller/chatting/ChattingRestController.java
src/main/java/com/example/myoceanproject/controller/main/MainController.java
src/main/resources/application.yml
src/main/resources/static/js/fix/chatting.js
src/main/resources/templates/app/fix/chattingAll.html
src/test/java/com/example/myoceanproject/dtoTest/ChattingTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupMemberTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java

채팅 목록 띄우기 성공

---

src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/resources/static/js/manager/admin_user_list.js
src/main/resources/templates/app/manager/admin_user_list.html

[20221204] 배다빈 

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/java/com/example/myoceanproject/repository/GroupCustomRepository.java
src/main/java/com/example/myoceanproject/repository/GroupRepositoryImpl.java
src/main/resources/static/js/community/detail.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html
src/test/java/com/example/myoceanproject/serviceTest/GroupServiceTest.java

[20221204 홍준성 -4]

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/repository/GroupCustomRepository.java
src/main/java/com/example/myoceanproject/service/GroupService.java
src/main/resources/static/js/community/detail.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/host/host.html

[20221205 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/type/CommunityCategory.java
src/main/resources/application.yml
src/main/resources/static/css/myList/myList.css
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/myList/myListBookBoard.html
src/main/resources/templates/app/myList/myListCookBoard.html
src/main/resources/templates/app/myList/myListCounselingBoard.html
src/main/resources/templates/app/myList/myListExerciseBoard.html
src/main/resources/templates/app/myList/myListFreeBoard.html
src/main/resources/templates/app/myList/myListMovieBoard.html
src/main/resources/templates/app/myList/myListTotal.html
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

이호영 2212050904 작업사항

---

src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/resources/templates/app/myList/myListTotal.html

이호영 2212051330 작업사항

---

src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/resources/application.yml
src/main/resources/static/css/manager/admin_user_list.css
src/main/resources/static/js/manager/admin_user_list.js
src/main/resources/templates/app/manager/admin_user_list.html
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

유저목록 restful로 변경

---

src/main/java/com/example/myoceanproject/controller/manager/ManagePostController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/controller/manager/ManagerController.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/main/resources/static/css/manager/admin_free_board.css
src/main/resources/static/js/manager/admin_free_board.js
src/main/resources/static/js/manager/admin_user_list.js
src/main/resources/templates/app/manager/admin_free_board.html

커뮤니티 관리 restFul로 변경
커뮤니티 게시글 불러오기(페아장, 검색)
커뮤니티 게시글 삭제

[20221206 - 배다빈]

---

src/main/java/com/example/myoceanproject/controller/myGroup/MyGroupController.java
src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/domain/DiaryDTO.java

이호영 2212061600 작업사항

---

src/main/java/com/example/myoceanproject/domain/QuestDTO.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/resources/application.yml

퀘스트DTO 수정
퀘스트 Entity  수정
.yml 파일 ddl-auto옵션 복구

[20221207 배다빈]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/java/com/example/myoceanproject/repository/DiaryRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/MyAskCustomRepository.java
src/main/java/com/example/myoceanproject/repository/MyAskRepository.java
src/main/java/com/example/myoceanproject/repository/MyAskRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/MyPostCustomRepository.java
src/main/java/com/example/myoceanproject/repository/MyPostRepository.java
src/main/java/com/example/myoceanproject/repository/MyPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/AskService.java
src/main/java/com/example/myoceanproject/service/DiaryService.java
src/main/java/com/example/myoceanproject/service/myPost/MyPostService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoLoginService.java
src/main/java/com/example/myoceanproject/type/GroupStatus.java
src/main/java/com/example/myoceanproject/type/UserLoginMethod.java
src/main/resources/application.yml
src/main/resources/static/css/Join/before_join.css
src/main/resources/templates/app/Join/before_join.html
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/fix/header.html
src/main/resources/templates/app/login/login.html
src/main/resources/templates/app/myGroup/myJoinGroup.html
src/main/resources/templates/app/myGroup/myOpenGroup.html

이호영 2212071755 작업사항

---

src/main/java/com/example/myoceanproject/controller/communtiy/CommunityController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityRestController.java
src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/main/java/com/example/myoceanproject/service/community/CommunityService.java
src/main/resources/application.yml
src/main/resources/static/js/community/community.js
src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/community/detail.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/community/community_comment.html
src/main/resources/templates/app/community/community_register.html
src/main/resources/templates/app/community/detail.html

[20221207 홍준성 -3]

---

src/main/java/com/example/myoceanproject/controller/manager/ManageQuestController.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/java/com/example/myoceanproject/service/QuestService.java
src/main/resources/static/css/manager/admin_free_board.css
src/main/resources/static/css/manager/admin_quest_list.css
src/main/resources/static/js/manager/admin_quest_list.js
src/main/resources/templates/app/manager/admin_quest_list.html

[20221208 배다빈]

---

src/main/java/com/example/myoceanproject/controller/main/IndexController.java
src/main/java/com/example/myoceanproject/controller/main/MainController.java
src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceController.java
src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceMonthController.java
src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceService.java
src/main/java/com/example/myoceanproject/repository/TodoListCustomRepository.java
src/main/java/com/example/myoceanproject/repository/TodoListCustomRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/TodoListRepository.java
src/main/java/com/example/myoceanproject/service/main/MainService.java
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/mySpace/mySpace.html
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java

[투두리스트] - Controller, Service, Repository, html,
- 로그인 유저 연동
- 투두리스트 수정, 삭제
- 일기페이지 이동
- 레스트 풀로 변경 [메인] - html, MainController, MainSercice
- 페이지 연결 타임리프로 변경
- 더미데이터 목록 불러오기

손호현, 22.12.08

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/java/com/example/myoceanproject/domain/AskDTO.java
src/main/java/com/example/myoceanproject/oauth/GoogleOAuthRequest.java
src/main/java/com/example/myoceanproject/oauth/GoogleOAuthResponse.java
src/main/java/com/example/myoceanproject/repository/MyAskCustomRepository.java
src/main/java/com/example/myoceanproject/repository/MyAskRepository.java
src/main/java/com/example/myoceanproject/repository/MyAskRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/AskService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleLoginService.java
src/main/java/com/example/myoceanproject/service/oAuth/NaverJoinService.java
src/main/java/com/example/myoceanproject/type/AskCategory.java
src/main/java/com/example/myoceanproject/type/AskStatus.java
src/main/resources/static/css/questionBoard/questionBoard.css
src/main/resources/templates/app/Join/before_join.html
src/main/resources/templates/app/fix/header.html
src/main/resources/templates/app/login/login.html
src/main/resources/templates/app/questionBoard/myQuestion.html

이호영 2212081031 작업사항

---

src/main/java/com/example/myoceanproject/controller/manager/DashboardController.java
src/main/java/com/example/myoceanproject/service/main/MainService.java
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html

[20221208 홍준성 -4]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/manager/DashboardController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/hadler/WebSocketHandler.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/community/reply/CommunityReplyRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/quest/QuestCustomRepository.java
src/main/java/com/example/myoceanproject/repository/quest/QuestRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/DashBoardService.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoJoinService.java
src/main/java/com/example/myoceanproject/type/UserAccountStatus.java
src/main/resources/static/js/manager/admin_dashboard.js
src/main/resources/templates/app/manager/admin_dashboard.html
src/test/java/com/example/myoceanproject/dtoTest/AskTest.java
src/test/java/com/example/myoceanproject/dtoTest/CommunityReplyTest.java
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java

[20221209 배다빈]

---

src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/resources/static/js/community/community.js
src/main/resources/static/js/host/host.js

[20221209 홍준성 -2]

---

src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/java/com/example/myoceanproject/domain/UserDTO.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/MyAskRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/AskService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleLoginService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoLoginService.java
src/main/java/com/example/myoceanproject/type/UserAccountStatus.java
src/main/java/com/example/myoceanproject/type/UserLoginMethod.java
src/main/resources/static/css/Join/before_join.css
src/main/resources/static/css/login/login.css
src/main/resources/static/css/myList/myList.css
src/main/resources/static/css/questionBoard/questionBoard.css
src/main/resources/static/js/questionBoard/questionBoard.js
src/main/resources/templates/app/Join/before_join.html
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/login/login.html
src/main/resources/templates/app/questionBoard/myQuestion.html

이호영 2212091611 작업사항

---

src/main/java/com/example/myoceanproject/config/CustomP6spySqlFormat.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityRestController.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostCustomRepository.java
src/main/java/com/example/myoceanproject/repository/community/post/CommunityPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/community/CommunityPostService.java
src/main/java/com/example/myoceanproject/service/community/CommunityService.java
src/main/java/com/example/myoceanproject/type/CommunityCategory.java
src/main/resources/application.yml
src/main/resources/static/css/community/community_write2.css
src/main/resources/static/js/community/community.js
src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/community/community.html

커뮤니티 게시판 좋아요, 무한스크롤, 댓글, 동적쿼리 버그 수정
게시판 게시글 및 게시판 오류 수정
추가 세팅 진행

[20221209 홍준성 -5, 6]

---

src/main/resources/static/js/host/host.js
src/main/resources/templates/app/host/host.html

[20221210 배다빈]

---

src/main/java/com/example/myoceanproject/controller/bulletin_board/BulletinboardRestController.java
src/main/java/com/example/myoceanproject/domain/CommunityPostDTO.java
src/main/java/com/example/myoceanproject/repository/GroupCustomRepository.java
src/main/java/com/example/myoceanproject/repository/GroupRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/GroupService.java
src/main/resources/static/css/bulletin_board/bulletin.css
src/main/resources/static/js/bulletin_board/bulletin_board.js
src/main/resources/static/js/community/community.js
src/main/resources/static/js/community/communityWrite.js
src/main/resources/templates/app/bulletin_board/bulletin_board.html
src/main/resources/templates/app/community/community.html

그룹 전체 게시판 레스트풀 완료
그룹 페이징 처리 완료

[20221210 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/manager/ManageQuestController.java
src/main/java/com/example/myoceanproject/controller/myAlarm/MyAlarmController.java
src/main/java/com/example/myoceanproject/controller/myAlarm/MyAlarmRestController.java
src/main/java/com/example/myoceanproject/domain/AlarmDTO.java
src/main/java/com/example/myoceanproject/domain/QuestDTO.java
src/main/java/com/example/myoceanproject/entity/Alarm.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmCustomRepository.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmRepository.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/alarm/AlarmService.java
src/main/java/com/example/myoceanproject/type/AlarmCategory.java
src/main/java/com/example/myoceanproject/type/QuestType.java
src/main/resources/static/js/manager/admin_quest_list.js
src/main/resources/static/js/myAlarm/myAlarm.js
src/main/resources/templates/app/manager/admin_quest_list.html
src/main/resources/templates/app/manager/admin_user_list.html
src/main/resources/templates/app/myAlarm/myAlarm.html

알림 저장하기(오늘의 퀘스트) 완료
알림 불러오기 완료
읽음/안읽음 처리 완료
----------------------------------
[진행중]
실시간 처리
댓글, 포인트, 질문 답변, 교환일기, 좋아요, 그룹 승인, 그룹 참가

[20221211 배다빈]

---

src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/controller/myPoint/MyPointController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QuestionBoardRestController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/java/com/example/myoceanproject/domain/PointDTO.java
src/main/java/com/example/myoceanproject/entity/Point.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/MyAskCustomRepository.java
src/main/java/com/example/myoceanproject/repository/MyAskRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/PointCustomRepository.java
src/main/java/com/example/myoceanproject/repository/PointRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/AskService.java
src/main/java/com/example/myoceanproject/service/PointService.java
src/main/java/com/example/myoceanproject/type/PointType.java
src/main/resources/static/css/myList/myList.css
src/main/resources/static/css/myPoint/myPoint.css
src/main/resources/static/css/questionBoard/questionBoard.css
src/main/resources/static/js/questionBoard/questionBoard.js
src/main/resources/templates/app/Join/before_join.html
src/main/resources/templates/app/login/login.html
src/main/resources/templates/app/myPoint/myPoint.html
src/main/resources/templates/app/questionBoard/myQuestion.html
src/main/resources/templates/app/questionBoard/questionPointInfo.html
src/main/resources/templates/app/questionBoard/questionQuestInfo.html
src/main/resources/templates/app/questionBoard/questionUserInfo.html
src/main/resources/templates/app/questionBoard/questionUsingInfo.html

이호영 2212112228 작업사항

---

src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/java/com/example/myoceanproject/repository/GroupCustomRepository.java
src/main/java/com/example/myoceanproject/repository/GroupRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/GroupBoardService.java
src/main/java/com/example/myoceanproject/service/GroupService.java
src/main/resources/static/js/community/community.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/host/host.html

[20221212 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/manager/ManageQuestController.java
src/main/java/com/example/myoceanproject/domain/AskDTO.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/java/com/example/myoceanproject/type/AskCategory.java
src/main/java/com/example/myoceanproject/type/AskStatus.java
src/main/java/com/example/myoceanproject/type/GroupStatus.java
src/main/resources/application.yml
src/main/resources/templates/app/manager/admin_questions.html
src/main/resources/templates/app/myAlarm/myAlarm.html

[20221212 배다빈]

---

src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/java/com/example/myoceanproject/domain/GroupDTO.java
src/main/java/com/example/myoceanproject/entity/CommunityPost.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/repository/GroupRepositoryImpl.java
src/main/resources/static/css/community/detail.css
src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/host/host.html

[20221212 홍준성 -5]

---

src/main/resources/static/js/community/community.js
src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/community/community_write.html
src/main/resources/templates/app/community/detail.html
src/main/resources/templates/app/host/host.html

모임과 같이 상세페이지 레이아웃 수정
일기 작성 시 태그 수정

[20221213 홍준성 -2]

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/aspect/annotation/AskAlarm.java
src/main/java/com/example/myoceanproject/aspect/annotation/GroupJoinAlarm.java
src/main/java/com/example/myoceanproject/aspect/annotation/PointAlarm.java
src/main/java/com/example/myoceanproject/aspect/annotation/RefundAlarm.java
src/main/java/com/example/myoceanproject/controller/myPoint/MyPointController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/java/com/example/myoceanproject/entity/User.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/PointService.java
src/main/java/com/example/myoceanproject/type/PointCheckType.java
src/main/java/com/example/myoceanproject/type/PointType.java
src/main/resources/static/js/myPoint/managerRefund.js
src/main/resources/static/js/myPoint/myPointRefund.js
src/main/resources/templates/app/myAlarm/myAlarm.html
src/main/resources/templates/app/myPoint/managerRefund.html
src/main/resources/templates/app/myPoint/myPointRefund.html

결제 퀘스트 달성 시 퀘스트 달성 알림, 보상 지급(벳지, 포인트)
포인트 환불 요청알림, 환불 완료 알림 완료
문의 사항에 관리자 답변 알림

[20221213 배다빈]

---

src/main/java/com/example/myoceanproject/controller/myQuest/MyQuestRestController.java
src/main/java/com/example/myoceanproject/repository/quest/QuestAchievementCustomRepository.java
src/main/java/com/example/myoceanproject/repository/quest/QuestAchievementRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/quest/QuestAchievementService.java
src/main/resources/static/css/myQuest/todayQuest.css
src/main/resources/static/js/myQuest/myBadge.js
src/main/resources/templates/app/myQuest/completeQuest.html
src/test/java/com/example/myoceanproject/serviceTest/QuestServiceTest.java

완료된 퀘스트 페이지 완료

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/config/WebMvcConfig.java
src/main/java/com/example/myoceanproject/controller/myAlarm/MyAlarmRestController.java
src/main/java/com/example/myoceanproject/interceptor/AlarmInterceptor.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/alarm/AlarmService.java
src/main/resources/static/js/fix/header.js

[20221214 배다빈]

---

src/main/java/com/example/myoceanproject/controller/myList/MyListController.java
src/main/java/com/example/myoceanproject/controller/myList/MyListRestController.java
src/main/java/com/example/myoceanproject/controller/myPage/MyPageController.java
src/main/java/com/example/myoceanproject/controller/myPage/MyPageRestController.java
src/main/java/com/example/myoceanproject/domain/DiaryDTO.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/repository/DiaryCustomRepository.java
src/main/java/com/example/myoceanproject/repository/DiaryRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/UserCustomRepository.java
src/main/java/com/example/myoceanproject/repository/UserRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/DiaryService.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/resources/static/js/myList/myDiary.js
src/main/resources/static/js/myPage/myPage.js
src/main/resources/templates/app/myList/myDiary.html
src/main/resources/templates/app/myPage/myPage.html

이호영 2212151147 작업사항

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/aspect/annotation/GroupAlarm.java
src/main/java/com/example/myoceanproject/config/WebMvcConfig.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageGroupController.java
src/main/java/com/example/myoceanproject/entity/Group.java
src/main/java/com/example/myoceanproject/interceptor/AlarmInterceptor.java
src/main/java/com/example/myoceanproject/repository/GroupRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/GroupService.java
src/main/resources/static/js/bulletin_board/bulletin_board_detail.js
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/manager/admin_group_open_request.html

그룹 승인 기능
그룹 상세보기로 이동
그룹 허가 알림
그룹 참여 알림 완료

[20221215 배다빈]

---

src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceController.java
src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceMonthController.java
src/main/java/com/example/myoceanproject/controller/mySpace/MySpaceService.java
src/main/java/com/example/myoceanproject/controller/search/SearchController.java
src/main/java/com/example/myoceanproject/controller/search/SearchHostRestController.java
src/main/java/com/example/myoceanproject/controller/search/SearchRestController.java
src/main/java/com/example/myoceanproject/repository/MyPostRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/TodoListCustomRepository.java
src/main/java/com/example/myoceanproject/repository/TodoListCustomRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/main/MainService.java
src/main/java/com/example/myoceanproject/service/search/SearchService.java
src/main/resources/static/js/fix/header.js
src/main/resources/templates/app/Search/NoSearch.html
src/main/resources/templates/app/Search/SearchResult.html
src/main/resources/templates/app/bulletin_board/bulletin_board.html
src/main/resources/templates/app/fix/header.html
src/main/resources/templates/app/fix/headerModify.html
src/test/java/com/example/myoceanproject/dtoTest/CommunityPostTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupScheduleTest.java
src/test/java/com/example/myoceanproject/dtoTest/GroupTest.java
src/test/java/com/example/myoceanproject/dtoTest/UserTest.java
src/test/java/com/example/myoceanproject/serviceTest/SearchTest.java
src/test/java/com/example/myoceanproject/serviceTest/Text.java

1. SearchController  - 통합검색 컨트롤러 구현
2. Main - 서비스단 최근 모임 게시글 4개 불러오기 수정
3. header에 검색바에서 엔터키로 검색 구현
4. 모임목록 페이지 헤더 검색바는 모임게시글만 검색으로 rest 방식 구현
5. 통합검색, 모임 검색 모두 검색결과 없을 시 검색 없음 이미지 구현
6. ToDoList 주석
7. MySpace 주석

손호현, 221215

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/domain/QuestDTO.java
src/main/java/com/example/myoceanproject/entity/Quest.java
src/main/resources/static/js/manager/admin_quest_list.js
src/main/resources/templates/app/manager/admin_quest_list.html

[20221216 배다빈]

---

src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html

[20221216 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/myList/MyListRestController.java
src/main/java/com/example/myoceanproject/domain/DiaryDTO.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/java/com/example/myoceanproject/repository/DiaryCustomRepository.java
src/main/java/com/example/myoceanproject/repository/DiaryRepository.java
src/main/java/com/example/myoceanproject/repository/DiaryRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/DiaryService.java
src/main/java/com/example/myoceanproject/type/DiaryCategory.java
src/main/resources/static/js/community/communityWrite.js
src/main/resources/templates/app/myList/myDiaryDetail.html
src/main/resources/templates/app/myList/myListBookBoard.html
src/main/resources/templates/app/myList/myListCookBoard.html
src/main/resources/templates/app/myList/myListCounselingBoard.html
src/main/resources/templates/app/myList/myListExerciseBoard.html
src/main/resources/templates/app/myList/myListFreeBoard.html
src/main/resources/templates/app/myList/myListMovieBoard.html
src/main/resources/templates/app/myList/myListTotal.html

이호영 2212161344 작업사항

---

src/main/java/com/example/myoceanproject/controller/main/MainController.java
src/main/java/com/example/myoceanproject/controller/search/SearchRestController.java
src/main/resources/static/js/fix/header.js
src/main/resources/templates/app/Search/SearchResult.html
src/main/resources/templates/app/bulletin_board/bulletin_board.html

헤더 엔터키 이벤트 수정
검색 후 댓글 목록 페이지 연결
모임, 검색 페이지 주석,
커밋 실수로 인한 커밋 되돌리기 후 복구

손호현 221216 작업사항

---

src/main/java/com/example/myoceanproject/controller/myList/MyListRestController.java
src/main/java/com/example/myoceanproject/controller/myPage/MyPageController.java
src/main/java/com/example/myoceanproject/repository/DiaryRepository.java
src/main/java/com/example/myoceanproject/repository/DiaryRepositoryImpl.java
src/main/java/com/example/myoceanproject/repository/GroupMemberRepository.java
src/main/java/com/example/myoceanproject/repository/GroupRepository.java
src/main/java/com/example/myoceanproject/repository/alarm/AlarmRepository.java
src/main/java/com/example/myoceanproject/repository/quest/QuestAchievementRepository.java
src/main/java/com/example/myoceanproject/service/DiaryService.java
src/main/resources/static/css/myPage/myPage.css
src/main/resources/static/js/community/communityWrite.js
src/main/resources/templates/app/fix/footer.html
src/main/resources/templates/app/myList/myList.html
src/main/resources/templates/app/myPage/myPage.html

이호영 2212170039 작업사항 확인부탁드립니다.
repository 부분에 카운트하는 메소드만 추가했습니다.

이호영 2212170039 작업사항

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/aspect/annotation/ExDiaryAlarm.java
src/main/java/com/example/myoceanproject/aspect/annotation/TodayAlarm.java
src/main/java/com/example/myoceanproject/controller/myQuest/MyQuestRestController.java
src/main/java/com/example/myoceanproject/repository/DiaryRepositoryImpl.java
src/main/java/com/example/myoceanproject/service/DiaryService.java
src/main/java/com/example/myoceanproject/type/AlarmCategory.java
src/main/resources/application.yml

[20221218] 배다빈

---

src/main/resources/static/js/bulletin_board/bulletin_board.js
src/main/resources/static/js/community/community.js
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/community/community_comment.html
src/main/resources/templates/app/community/community_register.html
src/main/resources/templates/app/community/community_write.html
src/main/resources/templates/app/community/detail.html

1. 커뮤니티 신고 모달창 수정
2. 커뮤니티 반응형 안나오던 오류 수정

[20221218 홍준성 -1]

---

src/main/java/com/example/myoceanproject/controller/myList/MyListRestController.java
src/main/resources/static/css/myList/myList.css
src/main/resources/templates/app/myList/myDiary.html

이호영 2212181600 페이지 변동사항 확인부탁드립니다.

이호영 2212181600 페이지 변동사항

---

src/main/java/com/example/myoceanproject/controller/bulletin_board/BulletinboardController.java
src/main/java/com/example/myoceanproject/controller/bulletin_board/BulletinboardRestController.java
src/main/resources/templates/app/bulletin_board/bulletin_board.html

[20221218 홍준성 -2]

---

src/main/java/com/example/myoceanproject/controller/manager/ManageAskController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageGroupController.java
src/main/java/com/example/myoceanproject/controller/manager/ManagePostController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageQuestController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageReplyController.java
src/main/java/com/example/myoceanproject/controller/manager/ManageUserController.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/resources/static/css/myQuest/todayQuest.css
src/main/resources/templates/app/manager/admin_counseling_board.html
src/main/resources/templates/app/manager/admin_counseling_board_reply.html
src/main/resources/templates/app/manager/admin_dashboard.html
src/main/resources/templates/app/manager/admin_free_board.html
src/main/resources/templates/app/manager/admin_free_board_reply.html
src/main/resources/templates/app/manager/admin_group_open_request.html
src/main/resources/templates/app/manager/admin_quest_list.html
src/main/resources/templates/app/manager/admin_questions.html
src/main/resources/templates/app/manager/admin_user_list.html
src/main/resources/templates/app/myAlarm/myAlarm.html

[20221218 배다빈]

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/controller/bulletin_board/BulletinboardRestController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityController.java
src/main/java/com/example/myoceanproject/controller/join/JoinController.java
src/main/java/com/example/myoceanproject/controller/login/LoginController.java
src/main/java/com/example/myoceanproject/service/UserService.java
src/main/java/com/example/myoceanproject/service/oAuth/GoogleJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/KakaoJoinService.java
src/main/java/com/example/myoceanproject/service/oAuth/NaverOAuthService.java
src/main/java/com/example/myoceanproject/type/AlarmCategory.java
src/main/resources/static/css/Join/before_join.css
src/main/resources/templates/app/Join/before_join.html

[20221218 홍준성 -3]

---

src/main/java/com/example/myoceanproject/controller/myPage/MyPageController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QuestionBoardRestController.java
src/main/java/com/example/myoceanproject/controller/questionBoard/QusetionBoardController.java
src/main/resources/static/js/questionBoard/usersQuestion.js
src/main/resources/templates/app/questionBoard/usersQuestion.html

이호영 2212182209 작업사항

---

src/main/java/com/example/myoceanproject/aspect/LogAspect.java
src/main/java/com/example/myoceanproject/controller/manager/ManageAskController.java
src/main/resources/templates/app/manager/admin_questions.html

[20221219 배다빈]

---

src/main/java/com/example/myoceanproject/controller/main/MainController.java
src/main/resources/templates/app/Main/main.html
src/main/resources/templates/app/Search/SearchResult.html

1. 메인 -고민상담 경로 변경
2. SearchResult 주석

손호현, 22.12.19

---

src/main/java/com/example/myoceanproject/repository/MyGroupRepositoryImpl.java
src/main/resources/static/css/myQuest/todayQuest.css
src/main/resources/static/js/myGroup/myJoinGroup.js
src/main/resources/static/js/myGroup/myOpenGroup.js
src/main/resources/templates/app/myGroup/myJoinGroup.html
src/main/resources/templates/app/myGroup/myOpenGroup.html

이호영 2212190918 작업사항

---

src/main/java/com/example/myoceanproject/controller/questionBoard/QuestionBoardRestController.java

이호영 2212190949 작업사항

---

src/main/java/com/example/myoceanproject/controller/communtiy/CommunityController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityLikeRestController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityReplyController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityReplyRestController.java
src/main/java/com/example/myoceanproject/controller/communtiy/CommunityRestController.java
src/main/java/com/example/myoceanproject/controller/host/HostController.java
src/main/java/com/example/myoceanproject/controller/host/HostRestController.java
src/main/resources/static/js/community/comment.js

controller 주석달기 + 커뮤니티 댓글 작성 유효성 검사 추가

[20221219 홍준성 -2]

---

src/main/resources/static/css/myList/myDiary.css

[20221219 홍준성 -3]

---

src/main/java/com/example/myoceanproject/entity/Ask.java
src/main/java/com/example/myoceanproject/entity/Diary.java
src/main/resources/templates/app/myPoint/myPoint.html

이호영 2212191323 작업사항 확인부탁드립니다.
diary content,ask content 더미데이터 넣을 때 길이가 작아서 @column 어노테이션 추가했습니다. create 한 번 해주시면 될 거 같습니다.

이호영 2212191323 작업사항

---

src/main/java/com/example/myoceanproject/controller/communtiy/CommunityReplyController.java
src/main/resources/static/css/community/detail.css
src/main/resources/static/css/myQuest/todayQuest.css
src/main/resources/static/js/bulletin_board/bulletin_board_detail.js
src/main/resources/static/js/community/comment.js
src/main/resources/static/js/community/community.js
src/main/resources/static/js/community/communityWrite.js
src/main/resources/static/js/community/detail.js
src/main/resources/static/js/host/host.js
src/main/resources/templates/app/bulletin_board/bulletin_board_detail.html
src/main/resources/templates/app/community/community.html
src/main/resources/templates/app/community/community_comment.html
src/main/resources/templates/app/community/community_register.html
src/main/resources/templates/app/host/host.html

더미데이터 및 커뮤니티/모임 alert창 모달로 모두 수정

[20221219 홍준성 -4]

---

src/main/resources/templates/app/fix/headerModify.html

[20221219 홍준성 -7]

---

src/main/resources/static/css/mySpace/mySpace.css
src/main/resources/templates/app/mySpace/mySpace.html

투두리스트 로그인안했을 시 모달, 확인 시 로그인 페이지 이동

투두리스트 로그인안했을 시 모달, 확인 시 로그인 페이지 이동

---

src/main/resources/templates/app/fix/header.html

[2022-12-20]
